# Generated by Django 5.2.15 on 2026-06-09 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_email_verification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('TEACHER', 'Teacher'), ('SUB_ADMIN', 'Sub Admin'), ('MAIN_ADMIN', 'Main Admin'), ('VISITOR', 'Visitor'), ('PLATFORM_ADMIN', 'Platform Admin')], db_index=True, max_length=20),
        ),
    ]
