# Generated by Django 5.2.15 on 2026-06-22 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_add_school_class'),
        ('users', '0004_user_avatar_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='student_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='schools.schoolclass'),
        ),
    ]
