import uuid
from django.db import models


class School(models.Model):
    """
    Global tenant registry. Every school-scoped row in the entire database
    carries a FK back to this table.

    is_active=False is the master kill-switch: the RLS policy at the
    database kernel will deny all access to that tenant's data.
    """
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255, unique=True)
    logo_url = models.URLField(blank=True)
    address = models.TextField(blank=True)
    contact_email = models.EmailField(blank=True)
    contact_phone = models.CharField(max_length=20, blank=True)
    is_active = models.BooleanField(default=True, db_index=True)
    onboarding_date = models.DateTimeField(auto_now_add=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'schools_school'
        ordering = ['name']

    def __str__(self):
        return self.name


class SchoolCulture(models.Model):
    """
    Philosophy and values uploaded by the school admin.
    Fed into the AI prompt context for generating student quotes,
    teacher tips, and admin leadership insights.
    """
    school = models.OneToOneField(
        School,
        on_delete=models.CASCADE,
        related_name='culture',
        primary_key=True,
    )
    philosophy = models.TextField(blank=True)
    mission_statement = models.TextField(blank=True)
    vision_statement = models.TextField(blank=True)
    core_values = models.TextField(blank=True)
    school_creed = models.TextField(blank=True)
    institutional_principles = models.TextField(blank=True)
    # Stored as [{quote: "...", author: "..."}, ...]
    founder_quotes = models.JSONField(default=list, blank=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'schools_schoolculture'

    def __str__(self):
        return f'Culture — {self.school.name}'


class DailyContent(models.Model):
    """
    Platform-wide or school-specific daily content (quotes, tips, insights).
    Generated by the AI scheduler and cached here for display.
    """
    CONTENT_TYPE_CHOICES = [
        ('STUDENT_QUOTE', 'Student Quote'),
        ('TEACHER_TIP', 'Teacher Tip'),
        ('ADMIN_INSIGHT', 'Admin Insight'),
    ]

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    # Null school = platform-wide fallback; set school = school-specific override
    school = models.ForeignKey(
        School,
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        related_name='daily_contents',
    )
    content_type = models.CharField(max_length=20, choices=CONTENT_TYPE_CHOICES, db_index=True)
    body = models.TextField()
    author = models.CharField(max_length=255, blank=True)
    display_date = models.DateField(db_index=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = 'schools_dailycontent'
        unique_together = [('school', 'content_type', 'display_date')]
        ordering = ['-display_date']

    def __str__(self):
        return f'{self.content_type} — {self.display_date}'
