# Generated by Django 5.2.15 on 2026-06-22 11:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentQuizPreferences',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('num_questions', models.PositiveSmallIntegerField(default=10)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('moderate', 'Moderate'), ('difficult', 'Difficult')], default='moderate', max_length=10)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.school')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'quiz_student_preferences',
            },
        ),
        migrations.CreateModel(
            name='TeacherSubjectThreshold',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(db_index=True, max_length=100)),
                ('min_questions', models.PositiveSmallIntegerField(default=5)),
                ('min_difficulty', models.CharField(choices=[('easy', 'Easy'), ('moderate', 'Moderate'), ('difficult', 'Difficult')], default='easy', max_length=10)),
                ('school', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='schools.school')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_thresholds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'quiz_teacher_threshold',
                'unique_together': {('school', 'teacher', 'subject')},
            },
        ),
    ]
