# Generated by Django 5.2.15 on 2026-06-08 02:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteUpload',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_url', models.CharField(help_text='S3/R2 URI', max_length=1024)),
                ('file_name', models.CharField(max_length=255)),
                ('note_type', models.CharField(choices=[('pdf', 'PDF'), ('image', 'Image'), ('voice', 'Voice Note'), ('text', 'Typed Text')], max_length=10)),
                ('file_size_bytes', models.PositiveIntegerField(default=0)),
                ('subject', models.CharField(blank=True, db_index=True, max_length=100)),
                ('topic', models.CharField(blank=True, max_length=100)),
                ('subtopic', models.CharField(blank=True, max_length=100)),
                ('raw_ocr_text', models.TextField(blank=True)),
                ('ai_summary_paragraph', models.TextField(blank=True)),
                ('ai_bullet_points', models.JSONField(default=list)),
                ('ai_key_points', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('PENDING_OCR', 'Pending OCR'), ('AWAITING_STUDENT_APPROVAL', 'Awaiting Student Approval'), ('PROCESSING_AI', 'Processing AI'), ('READY', 'Ready'), ('FAILED', 'Failed')], db_index=True, default='PENDING_OCR', max_length=30)),
                ('error_message', models.TextField(blank=True)),
                ('ocr_task_id', models.CharField(blank=True, max_length=255)),
                ('ai_task_id', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'notes_noteupload',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NoteConformityReport',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('conformity_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('similarity_analysis', models.TextField(blank=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='schools.school')),
            ],
            options={
                'db_table': 'notes_conformityreport',
            },
        ),
    ]
