# Generated by Django 5.2.15 on 2026-06-08 02:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notes', '0001_initial'),
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='noteupload',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='noteupload',
            name='school',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='schools.school'),
        ),
        migrations.AddField(
            model_name='noteconformityreport',
            name='student_note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conformity_reports_as_student', to='notes.noteupload'),
        ),
        migrations.AddField(
            model_name='noteconformityreport',
            name='teacher_note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conformity_reports_as_teacher', to='notes.noteupload'),
        ),
        migrations.AddIndex(
            model_name='noteupload',
            index=models.Index(fields=['owner', 'status'], name='idx_note_owner_status'),
        ),
        migrations.AddIndex(
            model_name='noteupload',
            index=models.Index(fields=['school', 'subject'], name='idx_note_school_subject'),
        ),
    ]
