# Generated by Django 5.2.15 on 2026-06-27 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_add_conformity_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noteupload',
            name='note_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('image', 'Image'), ('voice', 'Voice Note'), ('text', 'Typed Text'), ('doc', 'Document')], max_length=10),
        ),
    ]
