# Generated by Django 5.2.15 on 2026-07-01 15:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0008_conformity_teacher_lesson_doc'),
    ]

    operations = [
        migrations.AddField(
            model_name='noteconformityreport',
            name='last_run_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ConformityReportHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('conformity_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('similarity_analysis', models.TextField(blank=True)),
                ('matched_teacher_section', models.TextField(blank=True)),
                ('run_number', models.PositiveIntegerField(default=1)),
                ('snapshot_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='notes.noteconformityreport')),
            ],
            options={
                'db_table': 'notes_conformityreporthistory',
                'ordering': ['-snapshot_at'],
            },
        ),
    ]
