# Generated by Django 5.2.15 on 2026-06-16 13:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonPlan',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('subject', models.CharField(blank=True, db_index=True, max_length=100)),
                ('topic', models.CharField(blank=True, max_length=100)),
                ('subtopic', models.CharField(blank=True, max_length=100)),
                ('duration_minutes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('objective', models.TextField(blank=True)),
                ('materials_needed', models.TextField(blank=True)),
                ('introduction', models.TextField(blank=True)),
                ('main_content', models.TextField(blank=True)),
                ('activities', models.TextField(blank=True)),
                ('assessment', models.TextField(blank=True)),
                ('homework', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted for Review'), ('UNDER_REVIEW', 'Under Review'), ('REVISION_NEEDED', 'Revision Needed'), ('APPROVED', 'Approved')], db_index=True, default='DRAFT', max_length=20)),
                ('ai_suggestions', models.TextField(blank=True)),
                ('school', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='schools.school')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'teaching_lessonplan',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LessonPlanComment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_plan_comments', to=settings.AUTH_USER_MODEL)),
                ('lesson_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='teaching.lessonplan')),
            ],
            options={
                'db_table': 'teaching_lessonplancomment',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='lessonplan',
            index=models.Index(fields=['teacher', 'status'], name='idx_plan_teacher_status'),
        ),
        migrations.AddIndex(
            model_name='lessonplan',
            index=models.Index(fields=['school', 'status'], name='idx_plan_school_status'),
        ),
    ]
