# Generated by Django 5.2.15 on 2026-06-23 13:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_add_curriculum_type'),
        ('teaching', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonDocument',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doc_type', models.CharField(choices=[('plan', 'Lesson Plan'), ('note', 'Lesson Note')], db_index=True, max_length=10)),
                ('generation_mode', models.CharField(choices=[('ai', 'AI Generated'), ('upload', 'Upload & Analyze'), ('manual', 'Manually Written')], default='ai', max_length=10)),
                ('subject', models.CharField(db_index=True, max_length=100)),
                ('topic', models.CharField(max_length=200)),
                ('subtopic', models.CharField(blank=True, max_length=200)),
                ('class_level', models.CharField(max_length=50)),
                ('term', models.PositiveSmallIntegerField(default=1)),
                ('week', models.PositiveSmallIntegerField(default=1)),
                ('additional_context', models.TextField(blank=True)),
                ('title', models.CharField(blank=True, max_length=300)),
                ('content_markdown', models.TextField(blank=True)),
                ('board_summary', models.TextField(blank=True)),
                ('diagnostic_cards', models.JSONField(default=list)),
                ('resource_cards', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('generating', 'Generating'), ('submitted', 'Submitted for Review'), ('under_review', 'Under Review'), ('revision_needed', 'Revision Needed'), ('approved', 'Approved'), ('distributed', 'Distributed to Class')], db_index=True, default='draft', max_length=20)),
                ('ai_task_id', models.CharField(blank=True, max_length=255)),
                ('generation_error', models.TextField(blank=True)),
                ('approval_timestamp', models.DateTimeField(blank=True, null=True)),
                ('verification_hash', models.CharField(blank=True, max_length=64)),
                ('admin_comments', models.TextField(blank=True)),
                ('distributed_to_class', models.BooleanField(default=False)),
                ('distributed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_lesson_docs', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='schools.school')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_docs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'teaching_lessondocument',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LessonDocumentVersion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField()),
                ('content_markdown', models.TextField()),
                ('board_summary', models.TextField(blank=True)),
                ('change_note', models.TextField(blank=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='teaching.lessondocument')),
                ('saved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'teaching_lessondocumentversion',
                'ordering': ['-version_number'],
            },
        ),
        migrations.AddIndex(
            model_name='lessondocument',
            index=models.Index(fields=['teacher', 'status'], name='idx_ldoc_teacher_status'),
        ),
        migrations.AddIndex(
            model_name='lessondocument',
            index=models.Index(fields=['school', 'status'], name='idx_ldoc_school_status'),
        ),
        migrations.AddIndex(
            model_name='lessondocument',
            index=models.Index(fields=['school', 'doc_type'], name='idx_ldoc_school_type'),
        ),
        migrations.AlterUniqueTogether(
            name='lessondocumentversion',
            unique_together={('document', 'version_number')},
        ),
    ]
