from rest_framework import serializers
from .models import ConformityStatus, NoteConformityReport, NoteStatus, NoteType, NoteUpload

# Max 20 MB per file
MAX_FILE_SIZE_BYTES = 20 * 1024 * 1024

ALLOWED_MIME_TYPES = {
    'pdf': [
        'application/pdf',
        'application/x-pdf',
        'application/octet-stream',
    ],
    'image': [
        'image/jpeg', 'image/jpg', 'image/png', 'image/webp',
        'image/gif', 'image/tiff', 'image/bmp', 'image/heic', 'image/heif',
        'application/octet-stream',
    ],
    'voice': [
        'audio/mpeg', 'audio/mp3', 'audio/mp4', 'audio/m4a', 'audio/x-m4a',
        'audio/wav', 'audio/x-wav', 'audio/ogg', 'audio/webm',
        'audio/aac', 'audio/x-aac', 'audio/flac', 'audio/x-flac',
        'application/octet-stream',
    ],
    'text': [
        'text/plain',
        'text/plain; charset=utf-8',
        'text/plain;charset=utf-8',
        'application/octet-stream',
    ],
    'doc': [
        'application/msword',
        'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
        'application/vnd.ms-powerpoint',
        'application/vnd.openxmlformats-officedocument.presentationml.presentation',
        'application/vnd.ms-excel',
        'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
        'application/zip',
        'application/octet-stream',
    ],
}


class NoteUploadRequestSerializer(serializers.Serializer):
    """Validates a single-file upload (multipart/form-data)."""
    file = serializers.FileField()
    note_type = serializers.ChoiceField(choices=NoteType.choices)
    subject  = serializers.CharField(max_length=100, required=False, default='', allow_blank=True)
    topic    = serializers.CharField(max_length=100, required=False, default='', allow_blank=True)
    subtopic = serializers.CharField(max_length=100, required=False, default='', allow_blank=True)

    def validate(self, attrs):
        file_obj  = attrs['file']
        note_type = attrs['note_type']

        if file_obj.size > MAX_FILE_SIZE_BYTES:
            raise serializers.ValidationError(
                {'file': f'File size exceeds the 20 MB limit ({file_obj.size / 1024 / 1024:.1f} MB).'}
            )

        content_type = getattr(file_obj, 'content_type', '')
        allowed = ALLOWED_MIME_TYPES.get(note_type, [])
        if allowed and content_type and content_type not in allowed:
            raise serializers.ValidationError(
                {'file': f'File type "{content_type}" is not allowed for note_type "{note_type}".'}
            )

        return attrs


class NoteStatusSerializer(serializers.ModelSerializer):
    """Lightweight status-only response — used for polling."""
    class Meta:
        model  = NoteUpload
        fields = ('id', 'status', 'error_message', 'updated_at')
        read_only_fields = fields


class NoteListSerializer(serializers.ModelSerializer):
    """Compact card view for the notes list page."""
    class Meta:
        model  = NoteUpload
        fields = (
            'id', 'file_name', 'note_type',
            'subject', 'topic', 'subtopic',
            'status', 'created_at',
        )
        read_only_fields = fields


class NoteDetailSerializer(serializers.ModelSerializer):
    """Full note detail including AI output — shown after READY status."""
    owner_name = serializers.CharField(source='owner.full_name', read_only=True)
    # Explicit typing so the OpenAPI schema renders these as arrays of strings
    # rather than the generic "any" that JSONField produces by default.
    ai_bullet_points = serializers.ListField(
        child=serializers.CharField(), read_only=True,
        help_text='Bullet-point summary generated by the AI provider.',
    )
    ai_key_points = serializers.ListField(
        child=serializers.CharField(), read_only=True,
        help_text='Key learning points extracted by the AI provider.',
    )

    class Meta:
        model  = NoteUpload
        fields = (
            'id',
            'owner_name',
            'file_url',
            'file_name',
            'note_type',
            'file_size_bytes',
            'subject',
            'topic',
            'subtopic',
            # Pipeline output
            'raw_ocr_text',
            'ai_summary_paragraph',
            'ai_bullet_points',
            'ai_key_points',
            # State
            'status',
            'error_message',
            'created_at',
            'updated_at',
        )
        read_only_fields = fields


class NoteUpdateSerializer(serializers.ModelSerializer):
    """Allows updating subject/topic/subtopic after upload."""
    class Meta:
        model  = NoteUpload
        fields = ('subject', 'topic', 'subtopic')


class ConfirmOCRSerializer(serializers.Serializer):
    """
    Student-reviewed and corrected OCR text.
    Only after this confirmation does AI summarisation begin.
    """
    confirmed_text = serializers.CharField(
        help_text='Student-corrected OCR text. Triggers AI summarisation pipeline.',
        trim_whitespace=True,
    )

    def validate_confirmed_text(self, value):
        if len(value.strip()) < 10:
            raise serializers.ValidationError(
                'Confirmed text is too short. Please provide more content for the AI to summarise.'
            )
        return value.strip()


class BulkUploadResponseSerializer(serializers.Serializer):
    """Response shape for multi-file upload."""
    uploaded = NoteListSerializer(many=True)
    failed   = serializers.ListField(
        child=serializers.DictField(),
        help_text='List of {filename, error} for files that failed.',
    )


class SchoolNoteListSerializer(serializers.ModelSerializer):
    """Note list for teachers/admins browsing all notes in their school."""
    owner_name = serializers.CharField(source='owner.full_name', read_only=True)

    class Meta:
        model  = NoteUpload
        fields = (
            'id', 'owner_id', 'owner_name', 'file_name', 'note_type',
            'subject', 'topic', 'subtopic', 'status', 'created_at',
        )
        read_only_fields = fields


class ConformityReportSerializer(serializers.ModelSerializer):
    """Full conformity report — used for list and detail views."""
    student_note_id = serializers.UUIDField(source='student_note.id',           read_only=True)
    student_name    = serializers.CharField(source='student_note.owner.full_name', read_only=True)
    teacher_note_id = serializers.UUIDField(source='teacher_note.id',           read_only=True)
    subject         = serializers.CharField(source='student_note.subject',       read_only=True)

    class Meta:
        model  = NoteConformityReport
        fields = (
            'id',
            'student_note_id', 'student_name',
            'teacher_note_id',
            'subject',
            'conformity_percentage', 'similarity_analysis',
            'status', 'generated_at',
        )
        read_only_fields = fields


class ConformityReportCreateSerializer(serializers.Serializer):
    """Create a conformity report — teacher selects student note + their own reference note."""
    student_note_id = serializers.UUIDField(
        help_text="UUID of the student's READY note to evaluate."
    )
    teacher_note_id = serializers.UUIDField(
        help_text="UUID of the teacher's own READY reference note."
    )


class ConformityReportStatusSerializer(serializers.ModelSerializer):
    """Lightweight status polling for async conformity report generation."""
    class Meta:
        model  = NoteConformityReport
        fields = ('id', 'status', 'conformity_percentage', 'generated_at')
        read_only_fields = fields
