# Generated by Django 5.2.15 on 2026-06-08 02:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('logo_url', models.URLField(blank=True)),
                ('address', models.TextField(blank=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('onboarding_date', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'schools_school',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SchoolCulture',
            fields=[
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='culture', serialize=False, to='schools.school')),
                ('philosophy', models.TextField(blank=True)),
                ('mission_statement', models.TextField(blank=True)),
                ('vision_statement', models.TextField(blank=True)),
                ('core_values', models.TextField(blank=True)),
                ('school_creed', models.TextField(blank=True)),
                ('institutional_principles', models.TextField(blank=True)),
                ('founder_quotes', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'schools_schoolculture',
            },
        ),
        migrations.CreateModel(
            name='DailyContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content_type', models.CharField(choices=[('STUDENT_QUOTE', 'Student Quote'), ('TEACHER_TIP', 'Teacher Tip'), ('ADMIN_INSIGHT', 'Admin Insight')], db_index=True, max_length=20)),
                ('body', models.TextField()),
                ('author', models.CharField(blank=True, max_length=255)),
                ('display_date', models.DateField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_contents', to='schools.school')),
            ],
            options={
                'db_table': 'schools_dailycontent',
                'ordering': ['-display_date'],
                'unique_together': {('school', 'content_type', 'display_date')},
            },
        ),
    ]
