# Generated by Django 5.2.15 on 2026-06-22 14:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('school', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='schools.school')),
            ],
            options={
                'db_table': 'schools_class',
                'ordering': ['name'],
                'unique_together': {('school', 'name')},
            },
        ),
    ]
