# Generated by Django 5.2.15 on 2026-06-23 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_add_school_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='curriculum_type',
            field=models.CharField(choices=[('nerdc', 'NERDC (Nigerian)'), ('british', 'British / Cambridge'), ('american', 'American / Common Core'), ('blend_ng_uk', 'Nigeria + British Blend'), ('blend_ng_us', 'Nigeria + American Blend')], default='nerdc', help_text='The curriculum framework this school follows. Drives AI lesson generation.', max_length=20),
        ),
    ]
