# Generated by Django 5.2.15 on 2026-06-29 14:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_add_curriculum_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('is_general', models.BooleanField(default=False, help_text='If true this subject is shown to all classes; the classes M2M is ignored.')),
                ('classes', models.ManyToManyField(blank=True, help_text='Classes this subject is offered to (only used when is_general=False).', related_name='subjects', to='schools.schoolclass')),
                ('school', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='schools.school')),
            ],
            options={
                'db_table': 'schools_subject',
                'ordering': ['name'],
                'unique_together': {('school', 'name')},
            },
        ),
    ]
